### ISSUE TITLE
use_signals = False brings error when decorating class method

### ISSUE THREAD

**Issue by owneroxxor** [bitranox/wrapt-timeout-decorator#6]
```
from wrapt_timeout_decorator import *

class Foo(object):
    def __init__(self,x):
        self.x=x

    @timeout('instance.x', use_signals=False, dec_allow_eval=True)
    def foo2(self):
        print('swallow')

if __name__ == '__main__':
    my_foo = Foo(3)
    my_foo.foo2()
```

Above code gives this execution error:

```
Traceback (most recent call last):
  File "timeout_test.py", line 13, in <module>
    my_foo.foo2()
  File "/usr/local/python37/lib/python3.7/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 123, in wrapper
    if (not b_signals) and (not dill.pickles(wrapped)):
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 1419, in pickles
    pik = copy(obj, **kwds)
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 240, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 294, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 287, in dump
    pik.dump(obj)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 1078, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/python37/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 633, in save_reduce
    save(cls)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 1315, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/python37/lib/python3.7/pickle.py", line 786, in save_tuple
    save(element)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/python37/lib/python3.7/site-packages/dill/_dill.py", line 902, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/python37/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/local/python37/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
NotImplementedError: object proxy must define __reduce_ex__()
```

This fork from timeout-decorator really supports decorating classes methods?

**Comment by bitranox** [comment]
Yes I am sure that it works with classes. Let me check the Error You have got. 
You do this on Linux or on Windows ? 
Which Python Version ? 
Please let me know, in order to check.

**Comment by owneroxxor** [comment]
CentOS 6, 3.7.0

**Comment by bitranox** [comment]
let me check - I changed the implementation of signals = False  from Queue to Pipe recently - maybe there is some edge case I havebt tested ...  I will let You know.
Robert

**Comment by owneroxxor** [comment]
Nice. Also, take a look on the issue I opened in the parent fork of yours:

https://github.com/pnpnpn/timeout-decorator/issues/56

**Comment by bitranox** [comment]
I will check - since I handle the signals=False differently I need to check it.

**Comment by bitranox** [comment]
But now I need to take down the x-mas tree and have another coffee ...

**Comment by bitranox** [comment]
ok, fixed - some issue with the newest version of dill.
It should not have memory leaks - but please ceck yourself, and provide a small sample if You run into problems.

**Comment by bitranox** [comment]
check it out - i did some more fixing for use_signals = False
should work now
